/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.simplicity;


// import com.simplicity.Objek.ObjekBahanMakanan;

// public class App {
//     public static void main(String[] args) {
//         ObjekBahanMakanan[] daftar_bahan = new ObjekBahanMakanan[8];
//         daftar_bahan[0] = new ObjekBahanMakanan("Nasi\t", 5, 5);
//         daftar_bahan[1] = new ObjekBahanMakanan("Kentang", 3, 4);
//         daftar_bahan[2] = new ObjekBahanMakanan("Ayam\t", 10, 8);
//         daftar_bahan[3] = new ObjekBahanMakanan("Sapi\t", 12, 15);
//         daftar_bahan[4] = new ObjekBahanMakanan("Wortel\t", 3, 2);
//         daftar_bahan[5] = new ObjekBahanMakanan("Bayam\t", 3, 2);
//         daftar_bahan[6] = new ObjekBahanMakanan("Kacang\t", 2, 2);
//         daftar_bahan[7] = new ObjekBahanMakanan("Susu\t", 2, 1);
//         ObjekBahanMakanan.printArray(daftar_bahan);
//     }
// }

import com.simplicity.Objek.ObjekNonMakanan;



public class App {
    public static void main(String[] args) {
        ObjekNonMakanan o1 = new ObjekNonMakanan("Ayam", 1, 4, 50, null);
        ObjekNonMakanan o2 = new ObjekNonMakanan("Kucing", 2, 3, 70, null);
        Ruangan r1 = new Ruangan("Haha");
        Point point = new Point(0,0);
        Point point2 = new Point(0,4);
        if(r1.nabrakGa(o1,point,"h")){
            r1.tambahObjek(o1, point,"h");
        }
        else{
            System.out.println("Gabisa tambah bg");
        }
        if(r1.nabrakGa(o2,point2,"v")){
            r1.tambahObjek(o2, point2,"v");
        }
        else{
            System.out.println("Gabisa tambah bg");
        }
        
        r1.tampilkanRuangan();
        r1.tampilkanDaftarObjek();
        r1.hapusObjek(r1.getObjek(1));
        r1.tampilkanRuangan();
        r1.tampilkanDaftarObjek();
        r1.hapusObjek(r1.getObjek(0));
        //r1.hapusObjek(o2);
        r1.tampilkanRuangan();
        r1.tampilkanDaftarObjek();
    }
}
