/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.simplicity;

import com.simplicity.Util.GameManager;

public class App {
    public static void main(String[] args) {
        new GameManager();
    }
}
